### PR TITLE
Grab existing rowHeight

### PR DESCRIPTION
**Pull request by raytiley**
Without this fix the last item in the row will set the height, and if its smaller than any other items that's bad :P Will circle around and add tests when I have some time. Need to spend some time with the wife :)

### CODE REVIEW

**Comment by stefanpenner** [comment]
@raytiley can we get a test for this one? I would hate to regress.

**Comment by raytiley** [comment]
> @raytiley can we get a test for this one?

Yup. Will write one tomorrow.

**Comment by stefanpenner** [comment]
> Yup. Will write one tomorrow.

awesome thanks :)

**Comment by raytiley** [comment]
Test added.

**Comment by stefanpenner** [comment]
Do you have commit and npm publish? If not let me know I can add yoi

**Comment by raytiley** [comment]
Not yet. A release would be nice :)

**Comment by stefanpenner** [comment]
@raytiley done

**Pull request merged**
