### PR TITLE
Update "ember-cli-babel" to v6.8.2

### PR DESCRIPTION
**Pull request by Turbo87**
/cc @stefanpenner @rwjblue

### CODE REVIEW

**Comment by rwjblue** [comment]
LGTM (though I don't have merge access here).  I think this will ultimately need to be a 2.0.0 (due to dropping Node 0.12 support)...

**Comment by Turbo87** [comment]
yep

**Comment by rwjblue** [comment]
@stefanpenner - Ping?

**Comment by Turbo87** [comment]
Thanks @krisselden!

**Pull request merged**
